pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request is now in conflicts. Could you fix it? 🙏
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - status-success=continuous-integration/travis-ci/pr
      - status-success=deploy/netlify
    actions:
      merge:
        method: merge
      label:
        add:
          - performance
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=continuous-integration/travis-ci/pr
      - status-success=deploy/netlify
    actions:
      merge:
        method: merge
